# Generated by Django 5.1.3 on 2024-12-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_compra_preco'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default='2023-10-01 00:00:00'),
            preserve_default=False,
        ),
    ]
