# Generated by Django 5.1.3 on 2024-12-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_compra_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='data',
        ),
    ]
